// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYQcc3n3iIyA1JiTUqiB-7AilrPQ-QF4I',
    appId: '1:599379277705:web:c5f50180924cc93f26d358',
    messagingSenderId: '599379277705',
    projectId: 'st12-46f58',
    authDomain: 'st12-46f58.firebaseapp.com',
    storageBucket: 'st12-46f58.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuYrCWTsvhPInO4yDjUzbzEZDw205d974',
    appId: '1:599379277705:android:4c7a8b58974ffdd226d358',
    messagingSenderId: '599379277705',
    projectId: 'st12-46f58',
    storageBucket: 'st12-46f58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNCGn9GYflof0Crr2_n3FXhK93c3V3D1I',
    appId: '1:599379277705:ios:9ffc0882692206e326d358',
    messagingSenderId: '599379277705',
    projectId: 'st12-46f58',
    storageBucket: 'st12-46f58.firebasestorage.app',
    iosBundleId: 'com.example.st',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNCGn9GYflof0Crr2_n3FXhK93c3V3D1I',
    appId: '1:599379277705:ios:9ffc0882692206e326d358',
    messagingSenderId: '599379277705',
    projectId: 'st12-46f58',
    storageBucket: 'st12-46f58.firebasestorage.app',
    iosBundleId: 'com.example.st',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYQcc3n3iIyA1JiTUqiB-7AilrPQ-QF4I',
    appId: '1:599379277705:web:5748a6a98e12baec26d358',
    messagingSenderId: '599379277705',
    projectId: 'st12-46f58',
    authDomain: 'st12-46f58.firebaseapp.com',
    storageBucket: 'st12-46f58.firebasestorage.app',
  );

}